"use client";

import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

const translations: Record<string, Record<string, string>> = {
  ar: {
    "nav.home": "الرئيسية",
    "nav.services": "الخدمات",
    "nav.gallery": "معرض الأعمال",
    "nav.contact": "اتصل بنا",
    "nav.book": "احجز الآن",
    "hero.subtitle": "ZEDA BARBER SHOP",
    "hero.tagline": "سيب نفسك",
    "hero.book": "احجز موعدك الآن",
    "hero.work": "اتصل بنا",
    "services.title": "خدماتنا",
    "services.subtitle": "OUR SERVICES",
    "services.desc": "نقدم لكم مجموعة متكاملة من خدمات الحلاقة والعناية",
    "services.name1": "حلاقة شعر كلاسيكية",
    "services.name2": "تهذيب وتصفيف اللحية",
    "services.name3": "عناية كاملة بالوجه",
    "services.name4": "حلاقة شبابية عصرية",
    "services.name5": "قص أطفال",
    "services.name6": "تنظيف عميق للبشرة",
    "services.name7": "بكيدج العريس",
    "services.desc1": "حلاقة عصرية بتقنيات كلاسيكية احترافية تناسب جميع أنواع الشعر.",
    "services.desc2": "تشذيب وتصفيف اللحية بأعلى دقة باستخدام أفضل المنتجات.",
    "services.desc3": "جلسة عناية متكاملة للبشرة تشمل تنظيف وترطيب وتدليك.",
    "services.desc4": "أحدث صيحات الحلاقة الشبابية العصرية والمودرن.",
    "services.desc5": "قص شعر الأطفال بأسلوب لطيف ومريح يناسب جميع الأعمار.",
    "services.desc6": "إزالة الرؤوس السوداء وتنظيف عميق للبشرة بمستحضرات طبيعية.",
    "services.desc7": "باقة متكاملة للعريس تشمل حلاقة وتصفيف وعناية كاملة.",
    "services.book": "احجز",
    "team.title": "فريق العمل",
    "team.subtitle": "OUR TEAM",
    "team.desc": "فريق متكامل من أمهر الحلاقين لتقديم أفضل تجربة. كل أعضاء فريقنا مدربون على أحدث التقنيات.",
    "team.name1": "زيدا",
    "team.role1": "المؤسس والحلاق الأول",
    "team.exp1": "١٥ سنة خبرة",
    "team.name2": "معاذ",
    "team.role2": "حلاق محترف",
    "team.exp2": "١٠ سنوات خبرة",
    "team.name3": "مصطفى",
    "team.role3": "حلاق متخصص",
    "team.exp3": "٨ سنوات خبرة",
    "team.name4": "محمد",
    "team.role4": "حلاق أول",
    "team.exp4": "١٢ سنة خبرة",
    "team.name5": "عبدالله",
    "team.role5": "حلاق مبدع",
    "team.exp5": "٦ سنوات خبرة",
    "gallery.title": "معرض أعمالنا",
    "gallery.subtitle": "OUR GALLERY",
    "gallery.all": "عرض الكل",
    "gallery.desc": "جميع أعمالنا في مكان واحد",
    "cta.title": "كرسيك مستنيك",
    "cta.desc": "تواصل معنا للحجز أو الاستفسار. فريق ZEDA جاهز لخدمتك.",
    "cta.book": "احجز موعدك الآن",
    "cta.services": "جميع الخدمات",
    "footer.contact": "بيانات الاتصال",
    "footer.address": "العنوان",
    "footer.address_val": "كفرتصفا - كفرشكر - قليوبية",
    "footer.hours": "مواعيد العمل",
    "footer.hours_val": "السبت — الخميس: ١٠ص — ١١م\nالجمعة: بالحجز المسبق",
    "footer.phone": "الهاتف",
    "footer.phone_val": "01069389235",
    "footer.whatsapp": "واتساب",
    "footer.developer": "تصميم وتطوير",
    "footer.dev_by": "Developed by",
    "footer.dev_whatsapp": "واتساب المطور",
    "footer.copyright": "© 2026 ZEDA BARBER SHOP. All rights reserved.",
    "footer.follow": "تابعنا",
    "back.home": "العودة للرئيسية",
    "contact.title": "تواصل معنا",
    "contact.subtitle": "CONTACT",
    "contact.desc": "كرسيك في انتظارك. تواصل معنا للحجز أو الاستفسار. فريق ZEDA جاهز لخدمتك.",
    "contact.address": "العنوان",
    "contact.address_val": "كفرتصفا - كفرشكر - قليوبية",
    "contact.phone": "الهاتف",
    "contact.phone_val": "01069389235",
    "contact.hours": "مواعيد العمل",
    "contact.hours1": "السبت — الخميس: ١٠ص — ١١م",
    "contact.hours2": "الجمعة: بالحجز المسبق",
    "contact.book": "احجز الآن",
    "services_page.title": "خدماتنا",
    "services_page.subtitle": "OUR SERVICES",
    "services_page.desc": "نقدم لكم مجموعة متكاملة من خدمات الحلاقة والعناية",
    "services_page.book": "احجز الآن",
    "booking.step1": "اختر الخدمات",
    "booking.step1_desc": "اختر الخدمات التي تريدها",
    "booking.step2": "اختر الحلاق",
    "booking.step3": "اختر الموعد",
    "booking.step4": "تأكيد الحجز",
    "booking.next": "متابعة",
    "booking.prev": "السابق",
    "booking.name_label": "الاسم كامل",
    "booking.name_placeholder": "اكتب اسمك",
    "booking.summary": "ملخص الحجز",
    "booking.summary_services": "الخدمات",
    "booking.summary_barber": "الحلاق",
    "booking.summary_date": "التاريخ",
    "booking.summary_at": "الساعة",
    "booking.available_times": "المواعيد المتاحة",
    "booking.confirm": "تأكيد عبر واتساب",
    "booking.barber_any": "أول حلاق متاح",
    "booking.barber_any_title": "متاح",
    "booking.barber_any_desc": "اختر أقرب موعد متاح مع أي من حلاقينا",
  },
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact",
    "nav.book": "Book Now",
    "hero.subtitle": "ZEDA BARBER SHOP",
    "hero.tagline": "Leave It to Us",
    "hero.book": "Book Your Appointment",
    "hero.work": "Contact Us",
    "services.title": "Our Services",
    "services.subtitle": "OUR SERVICES",
    "services.desc": "A complete range of grooming and barber services tailored for you.",
    "services.name1": "Classic Haircut",
    "services.name2": "Beard Trim & Styling",
    "services.name3": "Full Facial Care",
    "services.name4": "Modern Youth Cut",
    "services.name5": "Kids Haircut",
    "services.name6": "Deep Skin Cleansing",
    "services.name7": "Groom Package",
    "services.desc1": "Modern cuts with classic techniques, suitable for all hair types.",
    "services.desc2": "Precision beard trimming and styling with premium products.",
    "services.desc3": "Complete facial care including cleansing, moisturizing, and massage.",
    "services.desc4": "The latest modern and trendy youth hairstyles.",
    "services.desc5": "Kid-friendly haircuts in a comfortable environment.",
    "services.desc6": "Blackhead removal and deep skin cleansing with natural products.",
    "services.desc7": "Complete groom package including haircut, styling, and full care.",
    "services.book": "Book",
    "team.title": "Our Team",
    "team.subtitle": "OUR TEAM",
    "team.desc": "A complete team of skilled barbers delivering the best experience. All our members are trained in the latest techniques.",
    "team.name1": "Zeda",
    "team.role1": "Founder & Lead Barber",
    "team.exp1": "15 years exp.",
    "team.name2": "Moaz",
    "team.role2": "Professional Barber",
    "team.exp2": "10 years exp.",
    "team.name3": "Mustafa",
    "team.role3": "Specialist Barber",
    "team.exp3": "8 years exp.",
    "team.name4": "Mohamed",
    "team.role4": "Senior Barber",
    "team.exp4": "12 years exp.",
    "team.name5": "Abdullah",
    "team.role5": "Creative Barber",
    "team.exp5": "6 years exp.",
    "gallery.title": "Our Gallery",
    "gallery.subtitle": "OUR GALLERY",
    "gallery.all": "View All",
    "gallery.desc": "All our work in one place",
    "cta.title": "Your Chair is Waiting",
    "cta.desc": "Contact us to book or inquire. The ZEDA team is ready to serve you.",
    "cta.book": "Book Your Appointment",
    "cta.services": "All Services",
    "footer.contact": "Contact Info",
    "footer.address": "Address",
    "footer.address_val": "Kafr Tisfa - Kafr Shokr - Qalyubia",
    "footer.hours": "Working Hours",
    "footer.hours_val": "Sat — Thu: 10AM — 11PM\nFri: By appointment",
    "footer.phone": "Phone",
    "footer.phone_val": "+20 106 938 9235",
    "footer.whatsapp": "WhatsApp",
    "footer.developer": "Designed & Developed by",
    "footer.dev_by": "Developed by",
    "footer.dev_whatsapp": "Developer WhatsApp",
    "footer.copyright": "© 2026 ZEDA BARBER SHOP. All rights reserved.",
    "footer.follow": "Follow Us",
    "back.home": "Back to Home",
    "contact.title": "Contact Us",
    "contact.subtitle": "CONTACT",
    "contact.desc": "Your chair awaits. Contact us to book or inquire. The ZEDA team is ready to serve you.",
    "contact.address": "Address",
    "contact.address_val": "Kafr Tisfa - Kafr Shokr - Qalyubia",
    "contact.phone": "Phone",
    "contact.phone_val": "+20 106 938 9235",
    "contact.hours": "Working Hours",
    "contact.hours1": "Sat — Thu: 10AM — 11PM",
    "contact.hours2": "Fri: By appointment",
    "contact.book": "Book Now",
    "services_page.title": "Our Services",
    "services_page.subtitle": "OUR SERVICES",
    "services_page.desc": "A complete range of grooming and barber services tailored for you.",
    "services_page.book": "Book Now",
    "booking.step1": "Choose Services",
    "booking.step1_desc": "Select the services you want",
    "booking.step2": "Choose Barber",
    "booking.step3": "Pick a Date",
    "booking.step4": "Confirm Booking",
    "booking.next": "Next",
    "booking.prev": "Back",
    "booking.name_label": "Full Name",
    "booking.name_placeholder": "Enter your name",
    "booking.summary": "Booking Summary",
    "booking.summary_services": "Services",
    "booking.summary_barber": "Barber",
    "booking.summary_date": "Date",
    "booking.summary_at": "at",
    "booking.available_times": "Available Times",
    "booking.confirm": "Confirm via WhatsApp",
    "booking.barber_any": "First Available",
    "booking.barber_any_title": "Available",
    "booking.barber_any_desc": "Choose the earliest available slot with any of our barbers",
  },
};

type Lang = "ar" | "en";

interface LangContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType>({
  lang: "ar",
  toggleLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("ar");

  const toggleLang = useCallback(() => {
    setLang((prev) => (prev === "ar" ? "en" : "ar"));
  }, []);

  const t = useCallback(
    (key: string) => translations[lang]?.[key] ?? key,
    [lang]
  );

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      <div dir={lang === "ar" ? "rtl" : "ltr"} lang={lang === "ar" ? "ar" : "en"}>
        {children}
      </div>
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
