import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#e9c176",
        "primary-container": "#c5a059",
        "outline-variant": "#4e4639",
        surface: "#121414",
        "on-tertiary": "#303030",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#d1c5b4",
        "surface-container-lowest": "#0c0f0f",
        "inverse-on-surface": "#2f3131",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-variant": "#333535",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed": "#261900",
        "on-secondary-container": "#bab8b7",
        "on-primary-fixed-variant": "#5d4201",
        background: "#121414",
        error: "#ffb4ab",
        "surface-dim": "#121414",
        "surface-bright": "#38393a",
        "surface-container": "#1e2020",
        "secondary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-surface": "#e2e2e2",
        "on-secondary": "#313030",
        "surface-container-high": "#282a2b",
        outline: "#9a8f80",
        "on-primary-container": "#4e3700",
        "on-secondary-fixed-variant": "#474646",
        "on-error": "#690005",
        primary: "#e9c176",
        "on-tertiary-container": "#3b3b3b",
        "surface-container-highest": "#333535",
        "primary-fixed": "#ffdea5",
        "secondary-container": "#4a4949",
        "on-primary": "#412d00",
        "on-tertiary-fixed-variant": "#474747",
        "tertiary-fixed-dim": "#c8c6c6",
        "tertiary-container": "#a7a5a5",
        "on-background": "#e2e2e2",
        "on-tertiary-fixed": "#1b1c1c",
        "inverse-primary": "#775a19",
        tertiary: "#c8c6c6",
        secondary: "#c9c6c5",
        "primary-fixed-dim": "#e9c176",
        "surface-container-low": "#1a1c1c",
        "tertiary-fixed": "#e4e2e1",
      },
      fontFamily: {
        "body-md": ["var(--font-cairo)", "sans-serif"],
        "body-lg": ["var(--font-cairo)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-cairo)", "sans-serif"],
        "display-lg-mobile": ["var(--font-cairo)", "sans-serif"],
        "headline-md": ["var(--font-cairo)", "sans-serif"],
        button: ["var(--font-cairo)", "sans-serif"],
        "label-caps": ["var(--font-cairo)", "sans-serif"],
        "display-lg": ["var(--font-cairo)", "sans-serif"],
        "headline-lg": ["var(--font-cairo)", "sans-serif"],
        tagline: ["var(--font-amiri)", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
      },
      spacing: {
        "margin-desktop": "80px",
        "container-max": "1440px",
        "section-gap": "160px",
        gutter: "32px",
        unit: "8px",
        "margin-mobile": "24px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
