// Auto-generated sidebar configuration
// Run: node scripts/generate.mjs

export const sidebar = [
  {
    text: 'Getting Started',
    items: [
      { text: 'Introduction', link: '/' },
      { text: 'Installation', link: '/installation' },
      { text: 'Quick Start', link: '/quick-start' },
      { text: 'Architecture', link: '/architecture' },
    ]
  },
  {
    text: 'Tutorials',
    items: [
      { text: 'Overview', link: '/tutorials/' },
      { text: 'Getting Started', link: '/tutorials/getting-started' },
      { text: 'Custom Agent', link: '/tutorials/custom-agent' },
      { text: 'Full-Stack Feature', link: '/tutorials/fullstack-feature' },
      { text: 'Security Workflow', link: '/tutorials/security-workflow' },
      { text: 'Performance Tuning', link: '/tutorials/performance-tuning' },
      { text: 'i18n Workflow', link: '/tutorials/i18n-workflow' },
    ]
  },
  {
    text: 'Workspace',
    items: [
      { text: 'Overview', link: '/workspace-overview' },
      { text: 'Folder Structure', link: '/folder-structure' },
      { text: 'Glossary', link: '/glossary' },
      { text: 'FAQ', link: '/faq' },
      { text: 'Troubleshooting', link: '/troubleshooting' },
      { text: 'Roadmap', link: '/roadmap' },
    ]
  },
  {
    text: 'Agents',
    collapsed: false,
    items: [
      { text: 'Overview', link: '/agents/' },
      { text: 'Accessibility', link: '/agents/accessibility' },
      { text: 'Ai Engineer', link: '/agents/ai-engineer' },
      { text: 'Api Designer', link: '/agents/api-designer' },
      { text: 'Architect', link: '/agents/architect' },
      { text: 'Backend', link: '/agents/backend' },
      { text: 'Cloud', link: '/agents/cloud' },
      { text: 'Context Engineer', link: '/agents/context-engineer' },
      { text: 'Database', link: '/agents/database' },
      { text: 'Designer', link: '/agents/designer' },
      { text: 'Devops', link: '/agents/devops' },
      { text: 'Docs Writer', link: '/agents/docs-writer' },
      { text: 'Ecommerce', link: '/agents/ecommerce' },
      { text: 'Frontend', link: '/agents/frontend' },
      { text: 'I18n', link: '/agents/i18n' },
      { text: 'Performance', link: '/agents/performance' },
      { text: 'Reviewer', link: '/agents/reviewer' },
      { text: 'Security', link: '/agents/security' },
      { text: 'Seo', link: '/agents/seo' },
      { text: 'Tester', link: '/agents/tester' }
    ]
  },
  {
    text: 'Skills',
    collapsed: false,
    items: [
      { text: 'Overview', link: '/skills/' },
      { text: 'Agent Design', link: '/skills/agent-design' },
      { text: 'Api Design', link: '/skills/api-design' },
      { text: 'Api Documentation', link: '/skills/api-documentation' },
      { text: 'Architecture Decisions', link: '/skills/architecture-decisions' },
      { text: 'Authentication Patterns', link: '/skills/authentication-patterns' },
      { text: 'Authorization Patterns', link: '/skills/authorization-patterns' },
      { text: 'Background Jobs', link: '/skills/background-jobs' },
      { text: 'Bundle Optimization', link: '/skills/bundle-optimization' },
      { text: 'Caching Strategies', link: '/skills/caching-strategies' },
      { text: 'Ci Cd Pipelines', link: '/skills/ci-cd-pipelines' },
      { text: 'Clean Architecture', link: '/skills/clean-architecture' },
      { text: 'Code Review Standards', link: '/skills/code-review-standards' },
      { text: 'Component Documentation', link: '/skills/component-documentation' },
      { text: 'Context Engineering', link: '/skills/context-engineering' },
      { text: 'Conversion Optimization', link: '/skills/conversion-optimization' },
      { text: 'Css Motion Design', link: '/skills/css-motion-design' },
      { text: 'Data Migration', link: '/skills/data-migration' },
      { text: 'Database Design', link: '/skills/database-design' },
      { text: 'Debug', link: '/skills/debug' },
      { text: 'Design Patterns', link: '/skills/design-patterns' },
      { text: 'Design Systems', link: '/skills/design-systems' },
      { text: 'Docker Patterns', link: '/skills/docker-patterns' },
      { text: 'Email Systems', link: '/skills/email-systems' },
      { text: 'Environment Secrets', link: '/skills/environment-secrets' },
      { text: 'Error Tracking', link: '/skills/error-tracking' },
      { text: 'Form Engineering', link: '/skills/form-engineering' },
      { text: 'I18n Architecture', link: '/skills/i18n-architecture' },
      { text: 'Image Optimization', link: '/skills/image-optimization' },
      { text: 'Infrastructure As Code', link: '/skills/infrastructure-as-code' },
      { text: 'Input Validation', link: '/skills/input-validation' },
      { text: 'Jwt Security', link: '/skills/jwt-security' },
      { text: 'Keyboard Navigation', link: '/skills/keyboard-navigation' },
      { text: 'Llm Integration', link: '/skills/llm-integration' },
      { text: 'Mcp Integration', link: '/skills/mcp-integration' },
      { text: 'Monitoring Observability', link: '/skills/monitoring-observability' },
      { text: 'Nextjs App Router', link: '/skills/nextjs-app-router' },
      { text: 'Nextjs Route Handlers', link: '/skills/nextjs-route-handlers' },
      { text: 'Owasp Top 10', link: '/skills/owasp-top-10' },
      { text: 'Playwright E2e', link: '/skills/playwright-e2e' },
      { text: 'Prisma Patterns', link: '/skills/prisma-patterns' },
      { text: 'Product Analytics', link: '/skills/product-analytics' },
      { text: 'Prompt Engineering', link: '/skills/prompt-engineering' },
      { text: 'Rag Patterns', link: '/skills/rag-patterns' },
      { text: 'Rate Limiting', link: '/skills/rate-limiting' },
      { text: 'React Patterns', link: '/skills/react-patterns' },
      { text: 'Realtime Patterns', link: '/skills/realtime-patterns' },
      { text: 'Refactoring Patterns', link: '/skills/refactoring-patterns' },
      { text: 'Responsive Design', link: '/skills/responsive-design' },
      { text: 'Rtl Engineering', link: '/skills/rtl-engineering' },
      { text: 'Scalability', link: '/skills/scalability' },
      { text: 'Screen Reader Patterns', link: '/skills/screen-reader-patterns' },
      { text: 'Security Audit', link: '/skills/security-audit' },
      { text: 'Solid Principles', link: '/skills/solid-principles' },
      { text: 'Sql Optimization', link: '/skills/sql-optimization' },
      { text: 'State Management', link: '/skills/state-management' },
      { text: 'Storage Patterns', link: '/skills/storage-patterns' },
      { text: 'Structured Logging', link: '/skills/structured-logging' },
      { text: 'Supabase Patterns', link: '/skills/supabase-patterns' },
      { text: 'Tailwind Css', link: '/skills/tailwind-css' },
      { text: 'Testing Strategy', link: '/skills/testing-strategy' },
      { text: 'Typography Systems', link: '/skills/typography-systems' },
      { text: 'Validate Workspace', link: '/skills/validate-workspace' },
      { text: 'Vercel Deployment', link: '/skills/vercel-deployment' },
      { text: 'Vitest Unit', link: '/skills/vitest-unit' },
      { text: 'Wcag Checklist', link: '/skills/wcag-checklist' },
      { text: 'Web Performance', link: '/skills/web-performance' },
      { text: 'Workspace Optimization', link: '/skills/workspace-optimization' }
    ]
  },
  {
    text: 'Commands',
    collapsed: false,
    items: [
      { text: 'Overview', link: '/commands/' },
      { text: '/a11y-audit', link: '/commands/a11y-audit' },
      { text: '/create-agent', link: '/commands/create-agent' },
      { text: '/create-skill', link: '/commands/create-skill' },
      { text: '/deploy-check', link: '/commands/deploy-check' },
      { text: '/generate-docs', link: '/commands/generate-docs' },
      { text: '/health-check', link: '/commands/health-check' },
      { text: '/new-api', link: '/commands/new-api' },
      { text: '/new-component', link: '/commands/new-component' },
      { text: '/new-page', link: '/commands/new-page' },
      { text: '/performance-check', link: '/commands/performance-check' },
      { text: '/refactor', link: '/commands/refactor' },
      { text: '/review', link: '/commands/review' },
      { text: '/security-scan', link: '/commands/security-scan' },
      { text: '/self-improve', link: '/commands/self-improve' },
      { text: '/seo-check', link: '/commands/seo-check' },
      { text: '/workspace-audit', link: '/commands/workspace-audit' },
      { text: '/workspace-validate', link: '/commands/workspace-validate' }
    ]
  },
  {
    text: 'Playbooks',
    collapsed: false,
    items: [
      { text: 'Overview', link: '/playbooks/' },
      { text: 'Ai Feature', link: '/playbooks/ai-feature' },
      { text: 'Api Development', link: '/playbooks/api-development' },
      { text: 'Backend Feature', link: '/playbooks/backend-feature' },
      { text: 'Bug Investigation', link: '/playbooks/bug-investigation' },
      { text: 'Code Review', link: '/playbooks/code-review' },
      { text: 'Database Migration', link: '/playbooks/database-migration' },
      { text: 'Deployment', link: '/playbooks/deployment' },
      { text: 'Documentation', link: '/playbooks/documentation' },
      { text: 'Feature Development', link: '/playbooks/feature-development' },
      { text: 'Frontend Feature', link: '/playbooks/frontend-feature' },
      { text: 'New Project', link: '/playbooks/new-project' },
      { text: 'Performance Optimization', link: '/playbooks/performance-optimization' },
      { text: 'Production Release', link: '/playbooks/production-release' },
      { text: 'Refactoring', link: '/playbooks/refactoring' },
      { text: 'Security Review', link: '/playbooks/security-review' },
      { text: 'Workspace Maintenance', link: '/playbooks/workspace-maintenance' }
    ]
  },
  {
    text: 'Generators',
    collapsed: false,
    items: [
      { text: 'Overview', link: '/generators/' },
      { text: 'Agent Generator', link: '/generators/agent-generator' },
      { text: 'Command Generator', link: '/generators/command-generator' },
      { text: 'Documentation Generator', link: '/generators/documentation-generator' },
      { text: 'Playbook Generator', link: '/generators/playbook-generator' },
      { text: 'Skill Generator', link: '/generators/skill-generator' },
      { text: 'Template Generator', link: '/generators/template-generator' }
    ]
  },
  {
    text: 'Knowledge Base',
    collapsed: false,
    items: [
      { text: 'Overview', link: '/knowledge/' },
      { text: 'Accessibility', link: '/knowledge/accessibility' },
      { text: 'Agent Design', link: '/knowledge/agent-design' },
      { text: 'Ai Engineering', link: '/knowledge/ai-engineering' },
      { text: 'Api Design', link: '/knowledge/api-design' },
      { text: 'Authentication', link: '/knowledge/authentication' },
      { text: 'Authorization', link: '/knowledge/authorization' },
      { text: 'Clean Architecture', link: '/knowledge/clean-architecture' },
      { text: 'Cloudflare', link: '/knowledge/cloudflare' },
      { text: 'Context Engineering', link: '/knowledge/context-engineering' },
      { text: 'Css', link: '/knowledge/css' },
      { text: 'Ddd', link: '/knowledge/ddd' },
      { text: 'Docker', link: '/knowledge/docker' },
      { text: 'Embeddings', link: '/knowledge/embeddings' },
      { text: 'Html', link: '/knowledge/html' },
      { text: 'Javascript', link: '/knowledge/javascript' },
      { text: 'Kubernetes', link: '/knowledge/kubernetes' },
      { text: 'Linux', link: '/knowledge/linux' },
      { text: 'Mcp', link: '/knowledge/mcp' },
      { text: 'Nextjs', link: '/knowledge/nextjs' },
      { text: 'Nodejs', link: '/knowledge/nodejs' },
      { text: 'Owasp', link: '/knowledge/owasp' },
      { text: 'Performance', link: '/knowledge/performance' },
      { text: 'Postgresql', link: '/knowledge/postgresql' },
      { text: 'Prisma', link: '/knowledge/prisma' },
      { text: 'Prompt Engineering', link: '/knowledge/prompt-engineering' },
      { text: 'Rag', link: '/knowledge/rag' },
      { text: 'React', link: '/knowledge/react' },
      { text: 'Seo', link: '/knowledge/seo' },
      { text: 'Solid', link: '/knowledge/solid' },
      { text: 'Supabase', link: '/knowledge/supabase' },
      { text: 'Tailwind Css', link: '/knowledge/tailwind-css' },
      { text: 'Tool Calling', link: '/knowledge/tool-calling' },
      { text: 'Typescript', link: '/knowledge/typescript' },
      { text: 'Vector Databases', link: '/knowledge/vector-databases' },
      { text: 'Vercel', link: '/knowledge/vercel' }
    ]
  },
  {
    text: 'Resources',
    collapsed: false,
    items: [
      { text: 'Examples', link: '/examples/' },
      { text: 'Templates', link: '/templates/' },
      { text: 'Memory System', link: '/memory/' },
      { text: 'Metrics', link: '/metrics/' },
      { text: 'Security', link: '/security/' },
      { text: 'Best Practices', link: '/best-practices/' },
    ]
  },
  {
    text: 'Release Notes',
    collapsed: false,
    items: [
      { text: 'v1.2 Stable', link: '/release-notes/v1.2' },
      { text: 'v1.1', link: '/release-notes/v1.1' },
      { text: 'v1.0', link: '/release-notes/v1.0' },
    ]
  },
]
